#!/usr/bin/bash
# for folder in */
# do
#     stow -D $folder
#     stow $folder
# done
#
# chsh -s $(which zsh)

# Syslink tmux
ln -s ~/.dotfiles/tmux ~/.config/tmux

# Create syslink for zshrc
ln -sf /home/thomas/.dotfiles/zsh/.zshrc /home/thomas/.zshrc

# Create syslink for nvim
ln -s ~/.dotfiles/nvim/.config/nvim/ ~/.config/nvim

# Create syslink for alacritty
ln -s ~/.dotfiles/alacritty/ ~/.config/alacritty

# Create syslinks for sway
ln -sf ~/.dotfiles/sway ~/.config/sway
ln -sf ~/.dotfiles/waybar ~/.config/waybar
ln -sf ~/.dotfiles/wofi ~/.config/wofi
ln -sf ~/.dotfiles/cava ~/.config/cava

# GNOME WORKSPACE SELECTION
# dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-5 "['<Super>5']"
# dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-5 "['<Super><Shift>5']" 
# dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-6 "['<Super>6']"
# dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-6 "['<Super><Shift>6']" 
# dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-7 "['<Super>7']"
# dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-7 "['<Super><Shift>7']" 
# dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-8 "['<Super>8']"
# dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-8 "['<Super><Shift>8']" 
# disable dynamic workspaces
# dconf write /org/gnome/mutter/dynamic-workspaces false
# set number of workspaces
# dconf write /org/gnome/desktop/wm/preferences/num-workspaces 8
