#!/bin/bash
FOLDER_PATH="/home/thomas/Pictures/walls/gruvbox"
IMAGE=($(ls $FOLDER_PATH | shuf -n 1))
swaybg -i "$FOLDER_PATH/$IMAGE" &
# restart wall_schedule
killall wall_schedule
/home/thomas/.config/hypr/scripts/wall_schedule &
