# Execute your favorite apps at launch
exec-once = waybar
exec-once = swaybg -i ~/.dotfiles/wallpaper/lantern.jpg
exec-once = hyprpm reload -n

# Dark mode settings
#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
