# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, 3840x2160@60, 0x0, 1.25
monitor = eDP-1, 1920x1200@60, 3072x0, 1.0

xwayland {
  force_zero_scaling = true
}

$terminal = foot
$fileManager = nautilus
$menu = wofi --show drun
$browser = app.zen_browser.zen

# Source other config files for better organization
source = ~/.dotfiles/hypr/animations.conf
source = ~/.dotfiles/hypr/env.conf
source = ~/.dotfiles/hypr/keybinds.conf
source = ~/.dotfiles/hypr/windrules.conf
source = ~/.dotfiles/hypr/autostart.conf

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # sensitivity=1.0 # for mouse cursor
    gaps_in=5
    gaps_out=20
    border_size=1
    no_border_on_floating=0

    col.active_border=rgba(D4BE98FF)
    col.inactive_border=rgba(ebdbb211)
    # apply_sens_to_raw=0
    resize_on_border=false
    layout = scrolling

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}
#
decoration {
     rounding=14
     dim_inactive=true
     dim_strength=0.1
     active_opacity= 0.99
     inactive_opacity=1
}

plugin {
    hyprscrolling {
        column_width = 0.95
        fullscreen_on_one_column = true
    }
}

misc {
    vfr = true
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true
}
